# Basic Python

## 1. Split this string

In [1]:
s = "Hi there Sam!"

In [2]:
x = s.split()
print(x)

['Hi', 'there', 'Sam!']


## 2. Use .format() to print the following string. 

### Output should be: The diameter of Earth is 12742 kilometers.

In [3]:
planet = "Earth"
diameter = 12742

In [4]:
print("The diameter of {0} is {1} kilometers.".format(planet, diameter));

The diameter of Earth is 12742 kilometers.


## 3. In this nest dictionary grab the word "hello"

In [5]:
d = {'k1':[1,2,3,{'tricky':['oh','man','inception',{'target':[1,2,3,'hello']}]}]}

In [6]:
d = {'k1':[1,2,3,{'tricky':['oh','man','inception',{'target':[1,2,3,'hello']}]}]}
print(d['k1'][3]["tricky"][3]['target'][3])

hello


# Numpy

In [7]:
import numpy as np

## 4.1 Create an array of 10 zeros? 
## 4.2 Create an array of 10 fives?

In [8]:
a = np.zeros(10)
print(a)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


In [9]:
a = np.ones(10)*5
print(a)

[5. 5. 5. 5. 5. 5. 5. 5. 5. 5.]


## 5. Create an array of all the even integers from 20 to 35

In [10]:
a = np.arange(10,25)
print(a)

[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24]


## 6. Create a 3x3 matrix with values ranging from 0 to 8

In [11]:
a = np.arange(9).reshape(3,3)
print(a)

[[0 1 2]
 [3 4 5]
 [6 7 8]]


## 7. Concatenate a and b 
## a = np.array([1, 2, 3]), b = np.array([4, 5, 6])

In [13]:
a = np.array([1,2,3])
b = np.array([4,5,6])
np.concatenate((a,b))

array([1, 2, 3, 4, 5, 6])

# Pandas

## 8. Create a dataframe with 3 rows and 2 columns

In [22]:
import pandas as pd 

1.Numpy Arrays

In [28]:
A = np.random.randint(10, size=(3,2))
df = pd.DataFrame(A,columns=['cola', 'colb'])
df

cola  colb
0     3     2
1     2     6
2     8     5

2.Dictionary

In [29]:
dict_a = {
   'col_a':[1,2,3], 
   'col_b': [2,5,6], 
}
df = pd.DataFrame(dict_a)
df

col_a  col_b
0      1      2
1      2      5
2      3      6

3.List

In [31]:
lst_a = [['Anne',23],['Roshni',24],['Jenifer',20]]
df = pd.DataFrame(lst_a,columns=['Name','Age'])
df

Name  Age
0     Anne   23
1   Roshni   24
2  Jenifer   20

## 9. Generate the series of dates from 1st Jan, 2023 to 10th Feb, 2023

In [32]:
import pandas as pd
df = pd.DataFrame()
df['time'] = pd.date_range(start="01/01/2023",end="10/02/2023", freq='24H')
df['day'] = df['time'].dt.day
df['month'] = df['time'].dt.month
df['year'] = df['time'].dt.year
df.head(len(df["time"]))


time  day  month  year
0   2023-01-01    1      1  2023
1   2023-01-02    2      1  2023
2   2023-01-03    3      1  2023
3   2023-01-04    4      1  2023
4   2023-01-05    5      1  2023
..         ...  ...    ...   ...
270 2023-09-28   28      9  2023
271 2023-09-29   29      9  2023
272 2023-09-30   30      9  2023
273 2023-10-01    1     10  2023
274 2023-10-02    2     10  2023

[275 rows x 4 columns]

## 10. Create 2D list to DataFrame

lists = [[1, 'aaa', 22],
         [2, 'bbb', 25],
         [3, 'ccc', 24]]

In [35]:
lists = [[1, 'aaa', 22], [2, 'bbb', 25], [3, 'ccc', 24]]

In [36]:
df = pd.DataFrame(lists, columns =['col1',"col2","col3"]) 
df

col1 col2  col3
0     1  aaa    22
1     2  bbb    25
2     3  ccc    24